---
#Kragle common vars
auto_deploy_node: 172.17.16.10
hanlon_base_url: http://{{ auto_deploy_node }}:8026/hanlon/api/v1/
dns1: 192.168.70.3

# Kragle site_discovery vars
pxe_subnet_name: 172.17.16.0
pxe_subnet_mask: 255.255.255.0
pxe_gateway: 172.17.16.1
pxe_dhcp_range_start: 172.17.16.20
pxe_dhcp_range_end: 172.17.16.50
domain_name: lordbusiness

hnl_mk_image: hnl_mk_debug-image.2.0.1.iso
hnl_mk_source: https://github.com/csc/Hanlon-Microkernel/releases/download/v2.0.1/
hnl_mk_local_path: /opt/hanlon/image/
hnl_mk_path: /home/hanlon/image/{{ hnl_mk_image }}

git_repos:
#  - { name: "wiley", repo: "git://github.com/csc/wiley", tag: "https://api.github.com/repos/csc/wiley/tags" }
  - { name: "slimer", repo: "git://github.com/csc/slimer", tag: "https://api.github.com/repos/csc/slimer/tags" }
  - { name: "kragle", repo: "git://github.com/csc/kragle", tag: "https://api.github.com/repos/csc/kragle/tags" }
  - { name: "ansible-scaleio", repo: "git://github.com/csc/ansible-scaleio", tag: "https://api.github.com/repos/csc/ansible-scaleio/tags" }

# offline variable should be set to true, when kragle is to be setup  without connection to the internet
offline: true

#offline Red Repository Pull variables

rhn_pass: rhn-pass  
rhn_user: rhn-user
pool: 'Red Hat Enterprise Linux OpenStack Platform Developer Supported Business Partner NFR'

repos:
  - rhel-7-server-rpms
  - rhel-7-server-openstack-6.0-rpms
  - rhel-server-rhscl-7-rpms
  - rhel-ha-for-rhel-7-server-rpms
  - rhel-7-server-optional-rpms
download_only: true
download_repo_path: '/root/download_repo'
shared_repo_path: '/var/www/html/repo'
repofile_location: '/root/'
